geändert:       lockroot

diff --git a/lockroot b/lockroot
--- a/lockroot
+++ b/lockroot
@@ -79,30 +79,27 @@ esac
 # import /usr/share/initramfs-tools/scripts/functions
 . /scripts/functions
 
-MYTAG="root-ro"
-DISABLE_MAGIC_FILE="/disable-root-ro"
+PKGNAME="lockroot"
+NOLOCK_FILE="/nolock"
 
 # parse kernel boot command line 
-ROOT_RO_DRIVER=
-DISABLE_ROOT_RO=
-for CMD_PARAM in $(cat /proc/cmdline); do
-    case ${CMD_PARAM} in
-        disable-root-ro=*)
-            DISABLE_ROOT_RO=${CMD_PARAM#disable-root-ro=}
-            ;;
-        root-ro-driver=*)
-            ROOT_RO_DRIVER=${CMD_PARAM#root-ro-driver=}
+NOLOCK=
+for PARAM in $(cat /proc/cmdline); do
+    case ${PARAM} in
+        nolock)
+            NOLOCK=true
             ;;
     esac
 done
 
 # check if read-only root fs is disabled
-if [ ! -z "${DISABLE_ROOT_RO}" ]; then
-    log_warning_msg "${MYTAG}: disabled, found boot parameter disable-root-ro=${DISABLE_ROOT_RO}"
+if [ ! "x${NOLOCK}" = "xtrue" ]; then
+    log_warning_msg "${PKGNAME}: disabled, found kernel boot parameter 'nonlock'"
     exit 0
 fi
-if [ -e "${rootmnt}${DISABLE_MAGIC_FILE}" ]; then
-    log_warning_msg "${MYTAG}: disabled, found file ${rootmnt}${DISABLE_MAGIC_FILE}"
+
+if [ -e "${rootmnt}${NOLOCK_FILE}" ]; then
+    log_warning_msg "${PKGNAME}: disabled, found file '${rootmnt}${NOLOCK_FILE}'"
     exit 0
 fi
 
@@ -110,86 +107,65 @@ fi
 # ${ROOT} and ${rootmnt} are predefined by caller of this script. Note that
 # the root fs ${rootmnt} it mounted readonly on the initrams, which fits nicely
 # for our purposes.
-ROOT_RO=/mnt/root-ro
-ROOT_RW=/mnt/root-rw
-ROOT_RW_UPPER=${ROOT_RW}/upper
-ROOT_RW_WORK=${ROOT_RW}/work
-
-# check if ${ROOT_RO_DRIVER} is defined, otherwise set default
-if [ -z "${ROOT_RO_DRIVER}" ]; then
-    ROOT_RO_DRIVER=overlay
-fi
-# settings based in ${ROOT_RO_DRIVER}, stop here if unsupported.
-case ${ROOT_RO_DRIVER} in
-    overlay)
-        MOUNT_PARMS="-t overlay -o lowerdir=${ROOT_RO},upperdir=${ROOT_RW_UPPER},workdir=${ROOT_RW_WORK} overlay ${rootmnt}"
-        ;;
-    aufs)
-        MOUNT_PARMS="-t aufs -o dirs=${ROOT_RW}:${ROOT_RO}=ro aufs-root ${rootmnt}"
-        ;;
-    *)
-        panic "${MYTAG} ERROR 1: invalid ROOT_RO_DRIVER ${ROOT_RO_DRIVER}"
-        ;;
-esac
-
+TMP_ROOT_RO=/mnt/ro
+TMP_ROOT_RW=/mnt/rw
+TMP_ROOT_RW_UPPER=${TMP_ROOT_RW}/upper
+TMP_ROOT_RW_WORK=${TMP_ROOT_RW}/work
+REAL_ROOT_RW=/.lock/rw
+REAL_ROOT_RO=/.lock/ro
 
 # check if kernel module exists
-modprobe -qb ${ROOT_RO_DRIVER}
+#modprobe -qb ${ROOT_RO_DRIVER}
+#if [ $? -ne 0 ]; then
+#    log_failure_msg "${PKGNAME} ERROR 2: missing kernel module ${ROOT_RO_DRIVER}"
+#    exit 0
+#fi
+
+# make the mount point on the init root fs ${TMP_ROOT_RW}
+[ -d ${TMP_ROOT_RW} ] || mkdir -p ${TMP_ROOT_RW}
 if [ $? -ne 0 ]; then
-    log_failure_msg "${MYTAG} ERROR 2: missing kernel module ${ROOT_RO_DRIVER}"
+    log_failure_msg "${PKGNAME}: ERROR 3: failed to create ${TMP_ROOT_RW}"
     exit 0
 fi
 
-# make the mount point on the init root fs ${ROOT_RW}
-[ -d ${ROOT_RW} ] || mkdir -p ${ROOT_RW}
+# make the mount point on the init root fs ${TMP_ROOT_RO}
+[ -d ${TMP_ROOT_RO} ] || mkdir -p ${TMP_ROOT_RO}
 if [ $? -ne 0 ]; then
-    log_failure_msg "${MYTAG} ERROR 3: failed to create ${ROOT_RW}"
+    log_failure_msg "${PKGNAME}: ERROR 4: failed to create ${TMP_ROOT_RO}"
     exit 0
 fi
 
-# make the mount point on the init root fs ${ROOT_RO}
-[ -d ${ROOT_RO} ] || mkdir -p ${ROOT_RO}
+# make the mount point on the init root fs ${TMP_ROOT_RW_WORK}
+[ -d ${TMP_ROOT_RW_WORK} ] || mkdir -p ${TMP_ROOT_RW_WORK}
 if [ $? -ne 0 ]; then
-    log_failure_msg "${MYTAG} ERROR 4: failed to create ${ROOT_RO}"
-    exit 0
-fi
-
-# make the mount point on the init root fs ${ROOT_WORKDIR}
-[ -d ${ROOT_WORKDIR} ] || mkdir -p ${ROOT_WORKDIR}
-if [ $? -ne 0 ]; then
-    log_failure_msg "${MYTAG} ERROR 5: failed to create ${ROOT_WORKDIR}"
+    log_failure_msg "${PKGNAME}: ERROR 5: failed to create ${TMP_ROOT_RW_WORK}"
     exit 0
 fi
 
 
-# mount a tempfs using the device name tmpfs-root at ${ROOT_RW}
-mount -t tmpfs tmpfs-root ${ROOT_RW}
+# mount a tempfs using the device name tmpfs-root at ${TMP_ROOT_RW}
+mount -t tmpfs tmpfs-root ${TMP_ROOT_RW}
 if [ $? -ne 0 ]; then
-    log_failure_msg "${MYTAG} ERROR 6: failed to create tmpfs"
+    log_failure_msg "${PKGNAME}: ERROR 6: failed to create tmpfs for root filesystem"
     exit 0
 fi
 
-if [ "${ROOT_RO_DRIVER}" = "overlay" ]; then
-
-    [ -d ${ROOT_RW_UPPER} ] || mkdir -p ${ROOT_RW_UPPER}
-    if [ $? -ne 0 ]; then
-        log_failure_msg "${MYTAG} ERROR 6.1: failed to create ${ROOT_RW_UPPER}"
-        exit 0
-    fi
-
-    [ -d ${ROOT_RW_WORK} ] || mkdir -p ${ROOT_RW_WORK}
-    if [ $? -ne 0 ]; then
-        log_failure_msg "${MYTAG} ERROR 6.2: failed to create ${ROOT_RW_WORK}"
-        exit 0
-    fi
-
+[ -d ${TMP_ROOT_RW_UPPER} ] || mkdir -p ${TMP_ROOT_RW_UPPER}
+if [ $? -ne 0 ]; then
+    log_failure_msg "${PKGNAME}: ERROR 6.1: failed to create ${TMP_ROOT_RW_UPPER}"
+    exit 0
 fi
 
-
-# root is mounted on ${rootmnt}, move it to ${ROOT_RO}.
-mount -o move ${rootmnt} ${ROOT_RO}
+[ -d ${TMP_ROOT_RW_WORK} ] || mkdir -p ${TMP_ROOT_RW_WORK}
 if [ $? -ne 0 ]; then
-    log_failure_msg "${MYTAG} ERROR 7: failed to move root away from ${rootmnt} to ${ROOT_RO}"
+    log_failure_msg "${PKGNAME}: ERROR 6.2: failed to create ${TMP_ROOT_RW_WORK}"
+    exit 0
+fi
+
+# root is mounted on ${rootmnt}, move it to ${TMP_ROOT_RO}.
+mount -o move ${rootmnt} ${TMP_ROOT_RO}
+if [ $? -ne 0 ]; then
+    log_failure_msg "${PKGNAME}: ERROR 7: failed to move root filesystem from ${rootmnt} to ${TMP_ROOT_RO}"
     exit 0
 fi
 
@@ -198,15 +174,15 @@ fi
 # "panic". Otherwise the boot process is very likely to fail with even more
 # errors and leave the system in a wired state.
 
-# mount virtual fs ${rootmnt} with rw-fs ${ROOT_RW} on top or ro-fs ${ROOT_RO}.
-mount ${MOUNT_PARMS}
+# mount virtual fs ${rootmnt} with rw-fs ${TMP_ROOT_RW} on top of ro-fs ${TMP_ROOT_RO}.
+mount -t overlay -o lowerdir=${TMP_ROOT_RO},upperdir=${TMP_ROOT_RW_UPPER},workdir=${TMP_ROOT_RW_WORK} overlay ${rootmnt}
 if [ $? -ne 0 ]; then
-    log_failure_msg "${MYTAG} ERROR 8: failed to create new ro/rw layerd ${rootmnt}"
+    log_failure_msg "${PKGNAME}: ERROR 8: failed to create overlay for root filesystem"
     # do recovery and try resoring the mount for ${rootmnt}
-    mount -o move ${ROOT_RO} ${rootmnt}
+    mount -o move ${TMP_ROOT_RO} ${rootmnt}
     if [ $? -ne 0 ]; then
        # thats bad, drop to shell to let the user try fixing this
-       panic "${MYTAG} RECOVERY ERROR: failed to move ${ROOT_RO} back to ${rootmnt}"
+       panic "${PKGNAME}: RECOVERY ERROR: failed to move root filesystem back to ${rootmnt}"
     fi
     exit 0
 fi
@@ -220,19 +196,19 @@ fi
 # Since the layered ro/rw is already up, these changes also end up on
 # ${ROOT_RW} while ${ROOT_RO} is not touched.
 
-# move mount from ${ROOT_RO} to ${rootmnt}${ROOT_RO}
-[ -d ${rootmnt}${ROOT_RO} ] || mkdir -p ${rootmnt}${ROOT_RO}
-mount -o move ${ROOT_RO} ${rootmnt}${ROOT_RO}
+# move mount from ${TMP_ROOT_RO} to ${rootmnt}${REAL_ROOT_RO}
+[ -d ${rootmnt}${REAL_ROOT_RO} ] || mkdir -p ${rootmnt}${REAL_ROOT_RO}
+mount -o move ${TMP_ROOT_RO} ${rootmnt}${REAL_ROOT_RO}
 if [ $? -ne 0 ]; then
-    log_failure_msg "${MYTAG} ERROR 9: failed to move ${ROOT_RO} to ${rootmnt}${ROOT_RO}"
+    log_failure_msg "${PKGNAME}: ERROR 9: failed to move ${TMP_ROOT_RO} to ${rootmnt}${REAL_ROOT_RO}"
     exit 0
 fi
 
-# move mount from ${ROOT_RW} to ${rootmnt}${ROOT_RW}
-[ -d ${rootmnt}${ROOT_RW} ] || mkdir -p ${rootmnt}${ROOT_RW}
-mount -o move ${ROOT_RW} ${rootmnt}${ROOT_RW}
+# move mount from ${TMP_ROOT_RW} to ${rootmnt}${REAL_ROOT_RW}
+[ -d ${rootmnt}${REAL_ROOT_RW} ] || mkdir -p ${rootmnt}${REAL_ROOT_RW}
+mount -o move ${TMP_ROOT_RW} ${rootmnt}${REAL_ROOT_RW}
 if [ $? -ne 0 ]; then
-    log_failure_msg "${MYTAG}: ERROR 10: failed to move ${ROOT_RW} to ${rootmnt}${ROOT_RW}"
+    log_failure_msg "${PKGNAME}: ERROR 10: failed to move ${TMP_ROOT_RW} to ${rootmnt}${REAL_ROOT_RW}"
     exit 0
 fi
 
@@ -248,43 +224,42 @@ fi
 #
 # Let's deal with /etc/fstab first. It usually contains an entry for the root
 # fs, which is no longer valid now. We have to remove it and add our new
-# ${ROOT_RO} entry.
+# ${REAL_ROOT_RO} entry.
 # Remember we are still on the initramfs root fs here, so we have to work on
-# ${rootmnt}/etc/fstab. The original fstab is ${rootmnt}${ROOT_RO}/etc/fstab.
-ROOT_TYPE=$(cat /proc/mounts | ${rootmnt}/bin/grep ${ROOT} | ${rootmnt}/usr/bin/cut -d' ' -f3)
-ROOT_OPTIONS=$(cat /proc/mounts | ${rootmnt}/bin/grep ${ROOT} | ${rootmnt}/usr/bin/cut -d' ' -f4)
+# ${rootmnt}/etc/fstab. The original fstab is ${rootmnt}${REAL_ROOT_RO}/etc/fstab.
+ROOT_FSTYPE_MNTOPTS=$(cat /proc/mounts | ${rootmnt}/bin/grep ${ROOT} | ${rootmnt}/usr/bin/cut -d' ' -f3,4)
 cat <<EOF >${rootmnt}/etc/fstab
 #
 #  This fstab is in RAM, the real one can be found at ${ROOT_RO}/etc/fstab
 #  The original entry for '/' and all swap files have been removed.  The new
 #  entry for the read-only the real root fs follows. Write access can be
 #  enabled using:
-#    sudo mount -o remount,rw ${ROOT_RO}
+#    sudo mount -o remount,rw ${REAL_ROOT_RO}
 #  re-mounting it read-only is done using:
-#    sudo mount -o remount,ro ${ROOT_RO}
+#    sudo mount -o remount,ro ${REAL_ROOT_RO}
 #
 
-${ROOT} ${ROOT_RO} ${ROOT_TYPE} ${ROOT_OPTIONS} 0 0
+${ROOT} ${REAL_ROOT_RO} ${ROOT_FSTYPE_MNTOPTS} 0 0
 
 #
-#  remaining entries from the original ${ROOT_RO}/etc/fstab follow.
+#  remaining entries from the original ${REAL_ROOT_RO}/etc/fstab follow.
 #
 EOF
 if [ $? -ne 0 ]; then
-    log_failure_msg "${MYTAG} ERROR 11: failed to modify /etc/fstab (step 1)"
+    log_failure_msg "${PKGNAME}: ERROR 11: failed to modify original root filsystem fstab entry"
     #exit 0
 fi
 
 #remove root entry and swap from fstab
-cat ${rootmnt}${ROOT_RO}/etc/fstab | ${rootmnt}/bin/grep -v ' / ' | ${rootmnt}/bin/grep -v swap >>${rootmnt}/etc/fstab
+cat ${rootmnt}${REAL_ROOT_RO}/etc/fstab | ${rootmnt}/bin/grep -v ' / ' | ${rootmnt}/bin/grep -v swap >>${rootmnt}/etc/fstab
 if [ $? -ne 0 ]; then
-    log_failure_msg "${MYTAG} ERROR 12: failed to modify etc/fstab (step 2)"
+    log_failure_msg "${PKGNAME}: ERROR 12: failed to delete fstab entries for root filesystem and swap"
     #exit 0
 fi
 
 # now we are done. Additinal steps may be necessary depending on the actualy
 # distribution and/or its configuration.
 
-log_success_msg "${MYTAG} sucessfully set up ro/tmpfs-rw layered root fs using ${ROOT_RO_DRIVER}"
+log_success_msg "${PKGNAME}: sucessfully set up overlay for root filesystem"
 
 exit 0
